services:
  - type: web
    name: forest-fire-backend
    env: python
    buildCommand: pip install -r ../requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: OPENWEATHER_KEY
        sync: false
      - key: FIRMS_MAP_KEY
        sync: false
